### ISSUE TITLE
can't start the cpanel service after build`

### ISSUE THREAD

**Issue by medicharlachiranjeevi** [mirhosting/cPanel-docker#7]
systemctl status cpanel.service
Failed to get D-Bus connection: Operation not permitted
and there is no cpanel running background

**Comment by mirhosting** [comment]
cPanel requires d-bus.
If you use it in environment which doesnt support d-bus, then it wont work. Mostly it means, that you run it on unprivileged container setup.

**Comment by mirhosting** [comment]
You may try this hint:
`docker run --tmpfs /run -v /sys/fs/cgroup:/sys/fs/cgroup:ro -d centos:7 /sbin/init`
from here:
https://github.com/CentOS/sig-cloud-instance-images/issues/45

**Comment by medicharlachiranjeevi** [comment]
its not working mysql is also not working

**Comment by mirhosting** [comment]
As I said, cPanel designed to run on fully supported privileged environment. You may use docker as template but it should be run on appropriate platform. It wont work on unprivileged platforms by design. You are welcome try to "hack" that, but I doubt if its possible at all.
